### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by st0at** [isign/client-bundle#1]
Hi,
Could you please tag a revision to have a stable version? Because now:

`composer require isign/client-bundle`
  ```
[InvalidArgumentException]                                                                                                                           
  Could not find package isign/client-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
```

**Comment by kuusas** [comment]
Hi,
thanks for opening very first issue on this repo :)
I tagged current stable version with tag v1.0, I hope that will solve your issue.
 https://github.com/isign/client-bundle/releases/tag/v1.0
